export * from './components/badge'
export * from './components/button'
export * from './components/card'
export * from './components/checkbox'
export * from './components/combobox'
export * from './components/context-menu'
export * from './components/context-menu-surface'
export * from './components/dialog'
export * from './components/dropdown-menu'
export * from './components/field-label'
export * from './components/gauge'
export * from './components/input'
export * from './components/label'
export * from './components/mini-bar'
export * from './components/panel'
export * from './components/layout'
export * from './components/password-input'
export * from './components/scrollable-dialog'
export * from './components/select'
export * from './components/sheet'
export * from './components/shell'
export * from './components/SizeProvider'
export * from './components/spinner'
export * from './components/stat-card'
export * from './components/status-badge'
export * from './components/summary-chips'
export * from './components/table'
export * from './components/tabs'
export * from './components/textarea'
export * from './components/view-toggle'

export * from './charts/RangePicker'
export * from './charts/Sparkline'
export * from './charts/TimeSeriesChart'
export * from './charts/MonitorChart'
export * from './charts/MonitorSkeleton'
export * from './charts/MetricsOverviewStrip'
// 全量对齐补录：它此前既漏在 barrel 外、又漏在边界测试清单外，于是主控台只能
// 自己留一份副本（见 apps/control-plane-web/src/components/charts/MetricComparePanel.tsx）。
export * from './charts/MetricComparePanel'

// 跨组件基础设施（FR-496 阶段 6）：焦点环/交互覆盖层常量与 a11y hooks
export * from './hooks'
export * from './lib/focus-ring'
export * from './lib/interaction-overlay'
export * from './lib/utils'
export * from './lib/threshold'
export * from './lib/brush'
export * from './lib/chart-hover'
export * from './lib/monitor-metrics'

// 业务视图（原 @jianmanager/biz-views 并入）：受控复合组件，不取数/不碰路由/不发请求/不弹 toast
export * from './components/views/TopLoadingBar'
export * from './components/views/ReleaseNotes'
export * from './components/views/UnifiedDiff'
export * from './components/views/UntrustedFieldBadge'
export * from './components/views/ClientDistFlowGuide'
export * from './components/views/bot-load/session/DisclaimerBanner'
export * from './components/views/client-dist/ObsTimeRangePicker'
export * from './components/views/console/BotHealthBar'
export * from './components/views/console/WorkspaceEmpty'
export * from './components/views/explorer/PromptDialog'
export * from './components/views/explorer/Toolbar'
export * from './components/views/explorer/editor/EditorShortcutsHelp'
export * from './components/views/file-browser/FileBrowserTree'

// ADR-097 起：应用业务组件按 a+b 双范式受控化并入，按域归档
export * from './components/views/nodes/NodePortsPanel'
export * from './components/views/nodes/NodeArtifactCachePanel'
export * from './components/views/nodes/NodeProbeVersionPanel'
export * from './components/views/nodes/NodeProxyPanel'
export * from './components/views/nodes/NodeGlobalPackagesSection'
export * from './components/views/nodes/NodeRepairPanel'
export * from './components/views/nodes/NodeLogRuntimePanel'
export * from './components/views/nodes/NodeRuntimeSection'
export * from './components/views/nodes/AddNodeDialog'
export * from './components/views/nodes/NodeJDKPanel'
export * from './components/views/nodes/PingNodeButton'
export * from './components/views/nodes/DirectoryPicker'

// instances 域（实例详情与控制台的分段/面板）
export * from './components/views/instances/HealthPanel'
export * from './components/views/instances/BinarySegment'
export * from './components/views/instances/InstanceEnvSegment'
export * from './components/views/instances/WorkspaceCard'
export * from './components/views/instances/RuntimeDriftNotice'
export * from './components/views/instances/InstancePicker'
export * from './components/views/instances/BinaryVersionPanel'
export * from './components/views/instances/SnapshotPanel'
export * from './components/views/instances/InstanceWorktableCard'
export * from './components/views/instances/ProcessPanel'
export * from './components/views/instances/MetricsFallbackSegment'
export * from './components/views/instances/MetricsTabSegment'
export * from './components/views/instances/InstanceTagsDialog'
export * from './components/views/instances/EditInstanceLimitsDialog'
export * from './components/views/instances/CreateBotDialog'
export * from './components/views/instances/InstanceBatchBar'
export * from './components/views/instances/RollingBatchDialog'
export * from './components/views/instances/ProxyRegistrationsDialog'
export * from './components/views/instances/EditInstanceConfigDialog'
export * from './components/views/instances/InstanceStatusDot'
export * from './components/views/instances/InstanceLibrary'
export * from './components/views/instances/InstanceGroupTree'
export * from './components/views/instances/InstanceGroupManager'
export * from './components/views/instances/ConfigSwitch'
export * from './components/views/instances/InstanceBackupSegment'
export * from './components/views/instances/CrashDiagnosticsCard'
export * from './components/views/instances/InstancePlayersSegment'
export * from './components/views/instances/ServerStateSegment'
export * from './components/views/instances/ServerSelector'
export * from './components/views/instances/InventorySegment'
export * from './components/views/instances/EconomySegment'
export * from './components/views/instances/BotStatusDot'
export * from './components/views/instances/BotSegment'
export * from './components/views/instances/MetricSourceChips'
export * from './components/views/instances/AttributionCard'
export * from './components/views/instances/CapacityForecastCard'
export * from './components/views/instances/MetricsSegment'
export * from './components/views/instances/PlayerTrendCard'
export * from './components/views/instances/SLOSection'
export * from './components/views/instances/InstanceRankingPanel'
export * from './components/views/instances/DrillTargetPicker'
export * from './components/views/instances/MonitoringPage'
export * from './components/views/instances/BusinessSegment'
export * from './components/views/CreateUserDialog'
export * from './components/views/CreateInvitationDialog'
export * from './components/views/CreateInstanceDialog'
export * from './components/views/instances/SidebarServerList'
export * from './components/views/instances/CommandPalette'
export * from './components/views/DangerConfirm'
export * from './components/views/InstanceWizardPage'
export * from './lib/instance-wizard-options'
export * from './components/views/TemplatesPage'
export * from './lib/template-apply'
export * from './lib/roles'
export * from './lib/nav-config'
export * from './lib/header-layout'
export * from './lib/sidebar-logo'
export * from './lib/task-status'
export * from './components/views/console/TasksMenu'
export * from './components/views/console/NotificationBell'
export * from './components/views/console/ClusterBadges'
export * from './components/views/console/AccountMenu'
export * from './lib/explorer-selection'
export * from './lib/explorer-clipboard'
export * from './lib/explorer-tabs'
export * from './lib/explorer-clipboard-bus'
export * from './lib/explorer-save-key'
export * from './components/views/explorer/FileList'
export * from './lib/file-entry'
export * from './lib/explorer-language'
export * from './lib/explorer-comment'
export * from './lib/explorer-ide-extensions'
export * from './components/views/explorer/CodeEditor'
export * from './components/views/explorer/DecompileViewer'
export * from './lib/archive-tree'
export * from './components/views/explorer/SearchPanel'
export * from './components/views/explorer/ArchiveViewer'
export * from './lib/file-version'
export * from './components/views/explorer/VersionDrawer'
export * from './lib/discard-guard'
export * from './lib/nav-history'
export * from './components/views/explorer/ResourceExplorer'
export * from './components/views/explorer/ExplorerTabHost'
export * from './lib/file-browser-capability'
export * from './components/views/file-browser/FilePreview'
export * from './components/views/file-browser/FileBrowser'
export * from './components/views/file-browser/UnifiedExplorerShell'
export * from './lib/storage-types'
// 显式列出而非 `export *`：`formatBytes` 与 `./lib/monitor-metrics` 同名（两者语义不同，
// 前者格式化存储占用、后者格式化监控指标），barrel 里不能同时通配导出。
// 需要存储版 `formatBytes` 的调用方走深路径 `@jianmanager/ui/lib/storage-view`。
export {
  deriveArchive,
  sortDirsByUsage,
  buildCrumbs,
  joinStoragePath,
} from './lib/storage-view'
export type { ArchiveDerived, Crumb } from './lib/storage-view'
export * from './lib/storage-source'
export * from './components/views/StoragePage'
export * from './components/views/console/BcSegment'
export * from './components/views/console/BcPlayersPanel'
export * from './components/views/console/InstanceActivityFeed'
export * from './components/views/console/TopologyGraph'
export * from './lib/node-types'
export * from './lib/node-summary'
export * from './lib/instance-summary'
export * from './lib/node-list'
export * from './lib/health-wall-types'
export * from './lib/health-wall'
export * from './lib/danger'
export * from './lib/instance-prefetch'
export * from './lib/console-log-types'
export * from './lib/capabilities'
export * from './lib/console-history'
export * from './lib/client-upload-plan'
export * from './lib/chunked-upload'
export * from './lib/efficient-upload'
export * from './lib/instance-grouping'
export * from './lib/instance-tree'
export * from './lib/instance-types'
export * from './lib/workspace-navigation'
export * from './lib/use-workspace-navigation'
export * from './lib/bot-load-types'
export * from './lib/bot-load-filters'
export * from './lib/bot-load-url-state'
export * from './lib/bot-load-report'
export * from './lib/bot-load-presets'
// 显式列出而非 `export *`：`formatBytes` 与 `./lib/monitor-metrics`、`FieldError` 与
// `./components/field-label` 同名（语义不同），barrel 里不能同时通配导出。
// 需要这两者的调用方走深路径 `@jianmanager/ui/lib/bot-load-metrics`。
export {
  LIVE_METRIC_MAX_POINTS,
  CHART_MAX_POINTS,
  clampChartPoints,
  formatLatencyMs,
  formatRatio,
  pickLatency,
  seriesWithNulls,
  appendMetricPoints,
} from './lib/bot-load-metrics'
// 同上：`FieldError` 与 `./components/field-label` 同名（此处是「校验错误条目」，
// 那边是「表单字段错误壳」）。需要本模块版的调用方走深路径。
export {
  validateCommandSchedule,
  validateLoadProfile,
  validateThresholds,
  validateConnection,
  validateCountMatchesProfile,
  previewBotNames,
} from './lib/bot-load-validation'
export * from './lib/bot-load-summaries'
export * from './lib/bot-load-draft'
export * from './lib/bot-load-session-store'
export * from './lib/bot-load-session-event-client'
export * from './lib/topology'
export * from './lib/inventory-view'
export * from './lib/director'
export * from './lib/quota-status'
export * from './lib/config-surface'
export * from './lib/terminal-session-manager'
export * from './components/views/console/DirectorSceneStrip'
export * from './components/views/console/QuotaPanel'
export * from './components/views/console/InstanceConfigSurfacePanel'
export * from './components/views/console/MobileConsoleNav'
export * from './components/views/console/ConsoleCommandBar'
export * from './lib/theme'
export * from './components/views/console/ThemeSwitcher'
export * from './components/views/console/SidebarNavLink'
export * from './components/views/console/WorkspaceSidebar'
export * from './components/views/console/ConsoleSidebar'
export * from './components/views/console/sidebar-link'
