// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: proto/worker.proto

package workerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerService_Register_FullMethodName             = "/worker.WorkerService/Register"
	WorkerService_Heartbeat_FullMethodName            = "/worker.WorkerService/Heartbeat"
	WorkerService_CreateInstance_FullMethodName       = "/worker.WorkerService/CreateInstance"
	WorkerService_StartInstance_FullMethodName        = "/worker.WorkerService/StartInstance"
	WorkerService_StopInstance_FullMethodName         = "/worker.WorkerService/StopInstance"
	WorkerService_RestartInstance_FullMethodName      = "/worker.WorkerService/RestartInstance"
	WorkerService_KillInstance_FullMethodName         = "/worker.WorkerService/KillInstance"
	WorkerService_SendCommand_FullMethodName          = "/worker.WorkerService/SendCommand"
	WorkerService_GetInstanceStatus_FullMethodName    = "/worker.WorkerService/GetInstanceStatus"
	WorkerService_ListInstances_FullMethodName        = "/worker.WorkerService/ListInstances"
	WorkerService_StreamInstanceEvents_FullMethodName = "/worker.WorkerService/StreamInstanceEvents"
	WorkerService_IssueTerminalToken_FullMethodName   = "/worker.WorkerService/IssueTerminalToken"
	WorkerService_ListFiles_FullMethodName            = "/worker.WorkerService/ListFiles"
	WorkerService_ReadFile_FullMethodName             = "/worker.WorkerService/ReadFile"
	WorkerService_WriteFile_FullMethodName            = "/worker.WorkerService/WriteFile"
	WorkerService_DeleteFile_FullMethodName           = "/worker.WorkerService/DeleteFile"
	WorkerService_RenameFile_FullMethodName           = "/worker.WorkerService/RenameFile"
	WorkerService_GetNodeMetrics_FullMethodName       = "/worker.WorkerService/GetNodeMetrics"
	WorkerService_GetInstanceMetrics_FullMethodName   = "/worker.WorkerService/GetInstanceMetrics"
)

// WorkerServiceClient is the client API for WorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkerService 定义 Control Plane 与 Worker Node 之间的 gRPC 服务。
type WorkerServiceClient interface {
	// Register Worker Node 首次启动时注册到 Control Plane。
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Heartbeat 双向心跳流，Worker 上报资源指标。
	Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatResponse], error)
	// CreateInstance 在指定 Worker 上创建实例。
	CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (*CreateInstanceResponse, error)
	// StartInstance 启动实例。
	StartInstance(ctx context.Context, in *InstanceActionRequest, opts ...grpc.CallOption) (*InstanceActionResponse, error)
	// StopInstance 停止实例。
	StopInstance(ctx context.Context, in *InstanceActionRequest, opts ...grpc.CallOption) (*InstanceActionResponse, error)
	// RestartInstance 重启实例。
	RestartInstance(ctx context.Context, in *InstanceActionRequest, opts ...grpc.CallOption) (*InstanceActionResponse, error)
	// KillInstance 强制终止实例。
	KillInstance(ctx context.Context, in *InstanceActionRequest, opts ...grpc.CallOption) (*InstanceActionResponse, error)
	// SendCommand 向实例发送命令。
	SendCommand(ctx context.Context, in *SendCommandRequest, opts ...grpc.CallOption) (*SendCommandResponse, error)
	// GetInstanceStatus 获取实例状态。
	GetInstanceStatus(ctx context.Context, in *InstanceActionRequest, opts ...grpc.CallOption) (*GetInstanceStatusResponse, error)
	// ListInstances 列出 Worker 上所有实例。
	ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (*ListInstancesResponse, error)
	// StreamInstanceEvents 订阅实例事件流。
	StreamInstanceEvents(ctx context.Context, in *StreamInstanceEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InstanceEvent], error)
	// IssueTerminalToken 签发一次性终端连接 token。
	IssueTerminalToken(ctx context.Context, in *IssueTerminalTokenRequest, opts ...grpc.CallOption) (*IssueTerminalTokenResponse, error)
	// ListFiles 列出实例工作目录下的文件。
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
	// ReadFile 读取文件内容。
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error)
	// WriteFile 写入文件内容。
	WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error)
	// DeleteFile 删除文件。
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error)
	// RenameFile 重命名文件。
	RenameFile(ctx context.Context, in *RenameFileRequest, opts ...grpc.CallOption) (*RenameFileResponse, error)
	// GetNodeMetrics 获取节点指标。
	GetNodeMetrics(ctx context.Context, in *GetNodeMetricsRequest, opts ...grpc.CallOption) (*GetNodeMetricsResponse, error)
	// GetInstanceMetrics 获取实例指标。
	GetInstanceMetrics(ctx context.Context, in *GetInstanceMetricsRequest, opts ...grpc.CallOption) (*GetInstanceMetricsResponse, error)
}

type workerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerServiceClient(cc grpc.ClientConnInterface) WorkerServiceClient {
	return &workerServiceClient{cc}
}

func (c *workerServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, WorkerService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerService_ServiceDesc.Streams[0], WorkerService_Heartbeat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HeartbeatRequest, HeartbeatResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_HeartbeatClient = grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatResponse]

func (c *workerServiceClient) CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (*CreateInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateInstanceResponse)
	err := c.cc.Invoke(ctx, WorkerService_CreateInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) StartInstance(ctx context.Context, in *InstanceActionRequest, opts ...grpc.CallOption) (*InstanceActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceActionResponse)
	err := c.cc.Invoke(ctx, WorkerService_StartInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) StopInstance(ctx context.Context, in *InstanceActionRequest, opts ...grpc.CallOption) (*InstanceActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceActionResponse)
	err := c.cc.Invoke(ctx, WorkerService_StopInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) RestartInstance(ctx context.Context, in *InstanceActionRequest, opts ...grpc.CallOption) (*InstanceActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceActionResponse)
	err := c.cc.Invoke(ctx, WorkerService_RestartInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) KillInstance(ctx context.Context, in *InstanceActionRequest, opts ...grpc.CallOption) (*InstanceActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceActionResponse)
	err := c.cc.Invoke(ctx, WorkerService_KillInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) SendCommand(ctx context.Context, in *SendCommandRequest, opts ...grpc.CallOption) (*SendCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendCommandResponse)
	err := c.cc.Invoke(ctx, WorkerService_SendCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) GetInstanceStatus(ctx context.Context, in *InstanceActionRequest, opts ...grpc.CallOption) (*GetInstanceStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInstanceStatusResponse)
	err := c.cc.Invoke(ctx, WorkerService_GetInstanceStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (*ListInstancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInstancesResponse)
	err := c.cc.Invoke(ctx, WorkerService_ListInstances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) StreamInstanceEvents(ctx context.Context, in *StreamInstanceEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InstanceEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerService_ServiceDesc.Streams[1], WorkerService_StreamInstanceEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamInstanceEventsRequest, InstanceEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_StreamInstanceEventsClient = grpc.ServerStreamingClient[InstanceEvent]

func (c *workerServiceClient) IssueTerminalToken(ctx context.Context, in *IssueTerminalTokenRequest, opts ...grpc.CallOption) (*IssueTerminalTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueTerminalTokenResponse)
	err := c.cc.Invoke(ctx, WorkerService_IssueTerminalToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, WorkerService_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadFileResponse)
	err := c.cc.Invoke(ctx, WorkerService_ReadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteFileResponse)
	err := c.cc.Invoke(ctx, WorkerService_WriteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFileResponse)
	err := c.cc.Invoke(ctx, WorkerService_DeleteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) RenameFile(ctx context.Context, in *RenameFileRequest, opts ...grpc.CallOption) (*RenameFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenameFileResponse)
	err := c.cc.Invoke(ctx, WorkerService_RenameFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) GetNodeMetrics(ctx context.Context, in *GetNodeMetricsRequest, opts ...grpc.CallOption) (*GetNodeMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeMetricsResponse)
	err := c.cc.Invoke(ctx, WorkerService_GetNodeMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) GetInstanceMetrics(ctx context.Context, in *GetInstanceMetricsRequest, opts ...grpc.CallOption) (*GetInstanceMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInstanceMetricsResponse)
	err := c.cc.Invoke(ctx, WorkerService_GetInstanceMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServiceServer is the server API for WorkerService service.
// All implementations must embed UnimplementedWorkerServiceServer
// for forward compatibility.
//
// WorkerService 定义 Control Plane 与 Worker Node 之间的 gRPC 服务。
type WorkerServiceServer interface {
	// Register Worker Node 首次启动时注册到 Control Plane。
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Heartbeat 双向心跳流，Worker 上报资源指标。
	Heartbeat(grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatResponse]) error
	// CreateInstance 在指定 Worker 上创建实例。
	CreateInstance(context.Context, *CreateInstanceRequest) (*CreateInstanceResponse, error)
	// StartInstance 启动实例。
	StartInstance(context.Context, *InstanceActionRequest) (*InstanceActionResponse, error)
	// StopInstance 停止实例。
	StopInstance(context.Context, *InstanceActionRequest) (*InstanceActionResponse, error)
	// RestartInstance 重启实例。
	RestartInstance(context.Context, *InstanceActionRequest) (*InstanceActionResponse, error)
	// KillInstance 强制终止实例。
	KillInstance(context.Context, *InstanceActionRequest) (*InstanceActionResponse, error)
	// SendCommand 向实例发送命令。
	SendCommand(context.Context, *SendCommandRequest) (*SendCommandResponse, error)
	// GetInstanceStatus 获取实例状态。
	GetInstanceStatus(context.Context, *InstanceActionRequest) (*GetInstanceStatusResponse, error)
	// ListInstances 列出 Worker 上所有实例。
	ListInstances(context.Context, *ListInstancesRequest) (*ListInstancesResponse, error)
	// StreamInstanceEvents 订阅实例事件流。
	StreamInstanceEvents(*StreamInstanceEventsRequest, grpc.ServerStreamingServer[InstanceEvent]) error
	// IssueTerminalToken 签发一次性终端连接 token。
	IssueTerminalToken(context.Context, *IssueTerminalTokenRequest) (*IssueTerminalTokenResponse, error)
	// ListFiles 列出实例工作目录下的文件。
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	// ReadFile 读取文件内容。
	ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error)
	// WriteFile 写入文件内容。
	WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error)
	// DeleteFile 删除文件。
	DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error)
	// RenameFile 重命名文件。
	RenameFile(context.Context, *RenameFileRequest) (*RenameFileResponse, error)
	// GetNodeMetrics 获取节点指标。
	GetNodeMetrics(context.Context, *GetNodeMetricsRequest) (*GetNodeMetricsResponse, error)
	// GetInstanceMetrics 获取实例指标。
	GetInstanceMetrics(context.Context, *GetInstanceMetricsRequest) (*GetInstanceMetricsResponse, error)
	mustEmbedUnimplementedWorkerServiceServer()
}

// UnimplementedWorkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerServiceServer struct{}

func (UnimplementedWorkerServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedWorkerServiceServer) Heartbeat(grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatResponse]) error {
	return status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedWorkerServiceServer) CreateInstance(context.Context, *CreateInstanceRequest) (*CreateInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateInstance not implemented")
}
func (UnimplementedWorkerServiceServer) StartInstance(context.Context, *InstanceActionRequest) (*InstanceActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartInstance not implemented")
}
func (UnimplementedWorkerServiceServer) StopInstance(context.Context, *InstanceActionRequest) (*InstanceActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopInstance not implemented")
}
func (UnimplementedWorkerServiceServer) RestartInstance(context.Context, *InstanceActionRequest) (*InstanceActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartInstance not implemented")
}
func (UnimplementedWorkerServiceServer) KillInstance(context.Context, *InstanceActionRequest) (*InstanceActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KillInstance not implemented")
}
func (UnimplementedWorkerServiceServer) SendCommand(context.Context, *SendCommandRequest) (*SendCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendCommand not implemented")
}
func (UnimplementedWorkerServiceServer) GetInstanceStatus(context.Context, *InstanceActionRequest) (*GetInstanceStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstanceStatus not implemented")
}
func (UnimplementedWorkerServiceServer) ListInstances(context.Context, *ListInstancesRequest) (*ListInstancesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInstances not implemented")
}
func (UnimplementedWorkerServiceServer) StreamInstanceEvents(*StreamInstanceEventsRequest, grpc.ServerStreamingServer[InstanceEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamInstanceEvents not implemented")
}
func (UnimplementedWorkerServiceServer) IssueTerminalToken(context.Context, *IssueTerminalTokenRequest) (*IssueTerminalTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueTerminalToken not implemented")
}
func (UnimplementedWorkerServiceServer) ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedWorkerServiceServer) ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedWorkerServiceServer) WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedWorkerServiceServer) DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedWorkerServiceServer) RenameFile(context.Context, *RenameFileRequest) (*RenameFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameFile not implemented")
}
func (UnimplementedWorkerServiceServer) GetNodeMetrics(context.Context, *GetNodeMetricsRequest) (*GetNodeMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeMetrics not implemented")
}
func (UnimplementedWorkerServiceServer) GetInstanceMetrics(context.Context, *GetInstanceMetricsRequest) (*GetInstanceMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstanceMetrics not implemented")
}
func (UnimplementedWorkerServiceServer) mustEmbedUnimplementedWorkerServiceServer() {}
func (UnimplementedWorkerServiceServer) testEmbeddedByValue()                       {}

// UnsafeWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServiceServer will
// result in compilation errors.
type UnsafeWorkerServiceServer interface {
	mustEmbedUnimplementedWorkerServiceServer()
}

func RegisterWorkerServiceServer(s grpc.ServiceRegistrar, srv WorkerServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerService_ServiceDesc, srv)
}

func _WorkerService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_Heartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkerServiceServer).Heartbeat(&grpc.GenericServerStream[HeartbeatRequest, HeartbeatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_HeartbeatServer = grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatResponse]

func _WorkerService_CreateInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).CreateInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_CreateInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).CreateInstance(ctx, req.(*CreateInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_StartInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).StartInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_StartInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).StartInstance(ctx, req.(*InstanceActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_StopInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).StopInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_StopInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).StopInstance(ctx, req.(*InstanceActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_RestartInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).RestartInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_RestartInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).RestartInstance(ctx, req.(*InstanceActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_KillInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).KillInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_KillInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).KillInstance(ctx, req.(*InstanceActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_SendCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).SendCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_SendCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).SendCommand(ctx, req.(*SendCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_GetInstanceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).GetInstanceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_GetInstanceStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).GetInstanceStatus(ctx, req.(*InstanceActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_ListInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).ListInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_ListInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).ListInstances(ctx, req.(*ListInstancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_StreamInstanceEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamInstanceEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerServiceServer).StreamInstanceEvents(m, &grpc.GenericServerStream[StreamInstanceEventsRequest, InstanceEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_StreamInstanceEventsServer = grpc.ServerStreamingServer[InstanceEvent]

func _WorkerService_IssueTerminalToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueTerminalTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).IssueTerminalToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_IssueTerminalToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).IssueTerminalToken(ctx, req.(*IssueTerminalTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).ListFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_ReadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).ReadFile(ctx, req.(*ReadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_WriteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).WriteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_WriteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).WriteFile(ctx, req.(*WriteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_RenameFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).RenameFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_RenameFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).RenameFile(ctx, req.(*RenameFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_GetNodeMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).GetNodeMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_GetNodeMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).GetNodeMetrics(ctx, req.(*GetNodeMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_GetInstanceMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).GetInstanceMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_GetInstanceMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).GetInstanceMetrics(ctx, req.(*GetInstanceMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerService_ServiceDesc is the grpc.ServiceDesc for WorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "worker.WorkerService",
	HandlerType: (*WorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _WorkerService_Register_Handler,
		},
		{
			MethodName: "CreateInstance",
			Handler:    _WorkerService_CreateInstance_Handler,
		},
		{
			MethodName: "StartInstance",
			Handler:    _WorkerService_StartInstance_Handler,
		},
		{
			MethodName: "StopInstance",
			Handler:    _WorkerService_StopInstance_Handler,
		},
		{
			MethodName: "RestartInstance",
			Handler:    _WorkerService_RestartInstance_Handler,
		},
		{
			MethodName: "KillInstance",
			Handler:    _WorkerService_KillInstance_Handler,
		},
		{
			MethodName: "SendCommand",
			Handler:    _WorkerService_SendCommand_Handler,
		},
		{
			MethodName: "GetInstanceStatus",
			Handler:    _WorkerService_GetInstanceStatus_Handler,
		},
		{
			MethodName: "ListInstances",
			Handler:    _WorkerService_ListInstances_Handler,
		},
		{
			MethodName: "IssueTerminalToken",
			Handler:    _WorkerService_IssueTerminalToken_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _WorkerService_ListFiles_Handler,
		},
		{
			MethodName: "ReadFile",
			Handler:    _WorkerService_ReadFile_Handler,
		},
		{
			MethodName: "WriteFile",
			Handler:    _WorkerService_WriteFile_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _WorkerService_DeleteFile_Handler,
		},
		{
			MethodName: "RenameFile",
			Handler:    _WorkerService_RenameFile_Handler,
		},
		{
			MethodName: "GetNodeMetrics",
			Handler:    _WorkerService_GetNodeMetrics_Handler,
		},
		{
			MethodName: "GetInstanceMetrics",
			Handler:    _WorkerService_GetInstanceMetrics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Heartbeat",
			Handler:       _WorkerService_Heartbeat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamInstanceEvents",
			Handler:       _WorkerService_StreamInstanceEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/worker.proto",
}
