// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/worker.proto

package workerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerService_Register_FullMethodName             = "/worker.WorkerService/Register"
	WorkerService_Heartbeat_FullMethodName            = "/worker.WorkerService/Heartbeat"
	WorkerService_CreateInstance_FullMethodName       = "/worker.WorkerService/CreateInstance"
	WorkerService_StartInstance_FullMethodName        = "/worker.WorkerService/StartInstance"
	WorkerService_StopInstance_FullMethodName         = "/worker.WorkerService/StopInstance"
	WorkerService_RestartInstance_FullMethodName      = "/worker.WorkerService/RestartInstance"
	WorkerService_KillInstance_FullMethodName         = "/worker.WorkerService/KillInstance"
	WorkerService_SendCommand_FullMethodName          = "/worker.WorkerService/SendCommand"
	WorkerService_GetInstanceStatus_FullMethodName    = "/worker.WorkerService/GetInstanceStatus"
	WorkerService_ListInstances_FullMethodName        = "/worker.WorkerService/ListInstances"
	WorkerService_StreamInstanceEvents_FullMethodName = "/worker.WorkerService/StreamInstanceEvents"
	WorkerService_IssueTerminalToken_FullMethodName   = "/worker.WorkerService/IssueTerminalToken"
	WorkerService_ListFiles_FullMethodName            = "/worker.WorkerService/ListFiles"
	WorkerService_ReadFile_FullMethodName             = "/worker.WorkerService/ReadFile"
	WorkerService_WriteFile_FullMethodName            = "/worker.WorkerService/WriteFile"
	WorkerService_DeleteFile_FullMethodName           = "/worker.WorkerService/DeleteFile"
	WorkerService_RenameFile_FullMethodName           = "/worker.WorkerService/RenameFile"
	WorkerService_DownloadArchive_FullMethodName      = "/worker.WorkerService/DownloadArchive"
	WorkerService_SearchFiles_FullMethodName          = "/worker.WorkerService/SearchFiles"
	WorkerService_ListArchiveEntries_FullMethodName   = "/worker.WorkerService/ListArchiveEntries"
	WorkerService_ReadArchiveEntry_FullMethodName     = "/worker.WorkerService/ReadArchiveEntry"
	WorkerService_DecompileClass_FullMethodName       = "/worker.WorkerService/DecompileClass"
	WorkerService_ListConfigFiles_FullMethodName      = "/worker.WorkerService/ListConfigFiles"
	WorkerService_ReadConfig_FullMethodName           = "/worker.WorkerService/ReadConfig"
	WorkerService_WriteConfig_FullMethodName          = "/worker.WorkerService/WriteConfig"
	WorkerService_ValidateConfig_FullMethodName       = "/worker.WorkerService/ValidateConfig"
	WorkerService_GetNodeMetrics_FullMethodName       = "/worker.WorkerService/GetNodeMetrics"
	WorkerService_GetInstanceMetrics_FullMethodName   = "/worker.WorkerService/GetInstanceMetrics"
	WorkerService_ListJDKs_FullMethodName             = "/worker.WorkerService/ListJDKs"
	WorkerService_InstallJDK_FullMethodName           = "/worker.WorkerService/InstallJDK"
	WorkerService_RemoveJDK_FullMethodName            = "/worker.WorkerService/RemoveJDK"
	WorkerService_DownloadCore_FullMethodName         = "/worker.WorkerService/DownloadCore"
	WorkerService_DeployServerProbe_FullMethodName    = "/worker.WorkerService/DeployServerProbe"
	WorkerService_CloneWorkDir_FullMethodName         = "/worker.WorkerService/CloneWorkDir"
	WorkerService_ListImages_FullMethodName           = "/worker.WorkerService/ListImages"
	WorkerService_PullImage_FullMethodName            = "/worker.WorkerService/PullImage"
	WorkerService_RemoveImage_FullMethodName          = "/worker.WorkerService/RemoveImage"
	WorkerService_CreateBackup_FullMethodName         = "/worker.WorkerService/CreateBackup"
	WorkerService_RestoreBackup_FullMethodName        = "/worker.WorkerService/RestoreBackup"
	WorkerService_CreateBot_FullMethodName            = "/worker.WorkerService/CreateBot"
	WorkerService_DeleteBot_FullMethodName            = "/worker.WorkerService/DeleteBot"
	WorkerService_ListBots_FullMethodName             = "/worker.WorkerService/ListBots"
	WorkerService_SetBotBehavior_FullMethodName       = "/worker.WorkerService/SetBotBehavior"
	WorkerService_SendBotCommand_FullMethodName       = "/worker.WorkerService/SendBotCommand"
	WorkerService_RunBotScript_FullMethodName         = "/worker.WorkerService/RunBotScript"
	WorkerService_StreamBotEvents_FullMethodName      = "/worker.WorkerService/StreamBotEvents"
	WorkerService_StreamPluginEvents_FullMethodName   = "/worker.WorkerService/StreamPluginEvents"
	WorkerService_SendPluginCommand_FullMethodName    = "/worker.WorkerService/SendPluginCommand"
	WorkerService_QueryServerState_FullMethodName     = "/worker.WorkerService/QueryServerState"
	WorkerService_GetVersion_FullMethodName           = "/worker.WorkerService/GetVersion"
	WorkerService_UpgradeWorker_FullMethodName        = "/worker.WorkerService/UpgradeWorker"
)

// WorkerServiceClient is the client API for WorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkerService 定义 Control Plane 与 Worker Node 之间的 gRPC 服务。
type WorkerServiceClient interface {
	// Register Worker Node 首次启动时注册到 Control Plane。
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Heartbeat 双向心跳流，Worker 上报资源指标。
	Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatResponse], error)
	// CreateInstance 在指定 Worker 上创建实例。
	CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (*CreateInstanceResponse, error)
	// StartInstance 启动实例。
	StartInstance(ctx context.Context, in *InstanceActionRequest, opts ...grpc.CallOption) (*InstanceActionResponse, error)
	// StopInstance 停止实例。
	StopInstance(ctx context.Context, in *InstanceActionRequest, opts ...grpc.CallOption) (*InstanceActionResponse, error)
	// RestartInstance 重启实例。
	RestartInstance(ctx context.Context, in *InstanceActionRequest, opts ...grpc.CallOption) (*InstanceActionResponse, error)
	// KillInstance 强制终止实例。
	KillInstance(ctx context.Context, in *InstanceActionRequest, opts ...grpc.CallOption) (*InstanceActionResponse, error)
	// SendCommand 向实例发送命令。
	SendCommand(ctx context.Context, in *SendCommandRequest, opts ...grpc.CallOption) (*SendCommandResponse, error)
	// GetInstanceStatus 获取实例状态。
	GetInstanceStatus(ctx context.Context, in *InstanceActionRequest, opts ...grpc.CallOption) (*GetInstanceStatusResponse, error)
	// ListInstances 列出 Worker 上所有实例。
	ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (*ListInstancesResponse, error)
	// StreamInstanceEvents 订阅实例事件流。
	StreamInstanceEvents(ctx context.Context, in *StreamInstanceEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InstanceEvent], error)
	// IssueTerminalToken 签发一次性终端连接 token。
	IssueTerminalToken(ctx context.Context, in *IssueTerminalTokenRequest, opts ...grpc.CallOption) (*IssueTerminalTokenResponse, error)
	// ListFiles 列出实例工作目录下的文件。
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
	// ReadFile 读取文件内容。
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error)
	// WriteFile 写入文件内容。
	WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error)
	// DeleteFile 删除文件。
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error)
	// RenameFile 重命名文件。
	RenameFile(ctx context.Context, in *RenameFileRequest, opts ...grpc.CallOption) (*RenameFileResponse, error)
	// DownloadArchive 把选中的文件/目录（目录递归）即时打包为 zip 并分块流式返回（FR-070 批量下载）。
	DownloadArchive(ctx context.Context, in *DownloadArchiveRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadArchiveChunk], error)
	// SearchFiles 对实例工作目录做全文搜索或文件名快速打开（FR-074，见 ADR-017）。
	// Worker 维护本地持久倒排索引（var/index/，增量更新），查询返回命中文件+行+片段。
	SearchFiles(ctx context.Context, in *SearchFilesRequest, opts ...grpc.CallOption) (*SearchFilesResponse, error)
	// ListArchiveEntries 列出归档（jar/zip）内全部条目（Go archive/zip，不起进程；FR-075，见 ADR-018）。
	ListArchiveEntries(ctx context.Context, in *ListArchiveEntriesRequest, opts ...grpc.CallOption) (*ListArchiveEntriesResponse, error)
	// ReadArchiveEntry 读取归档内某条目内容，流式截断到上限（FR-075）。
	ReadArchiveEntry(ctx context.Context, in *ReadArchiveEntryRequest, opts ...grpc.CallOption) (*ReadArchiveEntryResponse, error)
	// DecompileClass 经实例/系统 JDK 跑 CFR 反编译工作目录内 class/jar（或归档内某 class）为 Java 源码（FR-075，见 ADR-018）。
	DecompileClass(ctx context.Context, in *DecompileClassRequest, opts ...grpc.CallOption) (*DecompileClassResponse, error)
	// ListConfigFiles 列出可管理配置文件。
	ListConfigFiles(ctx context.Context, in *ListConfigFilesRequest, opts ...grpc.CallOption) (*ListConfigFilesResponse, error)
	// ReadConfig 读取配置文件并解析。
	ReadConfig(ctx context.Context, in *ReadConfigRequest, opts ...grpc.CallOption) (*ReadConfigResponse, error)
	// WriteConfig 写入配置文件。
	WriteConfig(ctx context.Context, in *WriteConfigRequest, opts ...grpc.CallOption) (*WriteConfigResponse, error)
	// ValidateConfig 校验配置内容。
	ValidateConfig(ctx context.Context, in *ValidateConfigRequest, opts ...grpc.CallOption) (*ValidateConfigResponse, error)
	// GetNodeMetrics 获取节点指标。
	GetNodeMetrics(ctx context.Context, in *GetNodeMetricsRequest, opts ...grpc.CallOption) (*GetNodeMetricsResponse, error)
	// GetInstanceMetrics 获取实例指标。
	GetInstanceMetrics(ctx context.Context, in *GetInstanceMetricsRequest, opts ...grpc.CallOption) (*GetInstanceMetricsResponse, error)
	// ListJDKs 列出 Worker 本地已注册/探测到的 JDK 目录。
	ListJDKs(ctx context.Context, in *ListJDKsRequest, opts ...grpc.CallOption) (*ListJDKsResponse, error)
	// InstallJDK 下载并安装指定 JDK 到 Worker 托管目录。
	InstallJDK(ctx context.Context, in *InstallJDKRequest, opts ...grpc.CallOption) (*InstallJDKResponse, error)
	// RemoveJDK 删除 Worker 托管的 JDK 目录。
	RemoveJDK(ctx context.Context, in *RemoveJDKRequest, opts ...grpc.CallOption) (*RemoveJDKResponse, error)
	// DownloadCore 下载服务端核心 jar 到实例工作目录（FR-034 一键开服）。
	DownloadCore(ctx context.Context, in *DownloadCoreRequest, opts ...grpc.CallOption) (*DownloadCoreResponse, error)
	// DeployServerProbe 部署 ServerProbe 监控探针 jar 与 config 到实例 plugins 目录（FR-010）。
	DeployServerProbe(ctx context.Context, in *DeployServerProbeRequest, opts ...grpc.CallOption) (*DeployServerProbeResponse, error)
	// CloneWorkDir 复制源实例工作目录到目标实例工作目录，排除运行态文件（FR-036 一键复制）。
	CloneWorkDir(ctx context.Context, in *CloneWorkDirRequest, opts ...grpc.CallOption) (*CloneWorkDirResponse, error)
	// ListImages 列出 Worker 本机 Docker 镜像。
	ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error)
	// PullImage 从 registry 拉取镜像到 Worker 本机（建实例选镜像前置）。
	PullImage(ctx context.Context, in *PullImageRequest, opts ...grpc.CallOption) (*PullImageResponse, error)
	// RemoveImage 删除 Worker 本机 Docker 镜像。
	RemoveImage(ctx context.Context, in *RemoveImageRequest, opts ...grpc.CallOption) (*RemoveImageResponse, error)
	// CreateBackup 将实例工作目录打包为 tar.gz 落到节点数据根 var/backups/。
	// 增量备份据 base_manifest 仅打包新增/变化文件；可选上传到远程存储后端。
	CreateBackup(ctx context.Context, in *CreateBackupRequest, opts ...grpc.CallOption) (*CreateBackupResponse, error)
	// RestoreBackup 按备份链顺序（全量基 + 各增量）回放归档到实例工作目录；
	// 远程归档先据 storage 拉回本地再回放。
	RestoreBackup(ctx context.Context, in *RestoreBackupRequest, opts ...grpc.CallOption) (*RestoreBackupResponse, error)
	// CreateBot 在 Worker 上创建 Bot 连接。
	CreateBot(ctx context.Context, in *CreateBotRequest, opts ...grpc.CallOption) (*CreateBotResponse, error)
	// DeleteBot 停止并删除 Bot。
	DeleteBot(ctx context.Context, in *DeleteBotRequest, opts ...grpc.CallOption) (*DeleteBotResponse, error)
	// ListBots 列出 Worker 上所有 Bot。
	ListBots(ctx context.Context, in *ListBotsRequest, opts ...grpc.CallOption) (*ListBotsResponse, error)
	// SetBotBehavior 切换 Bot 行为模式。
	SetBotBehavior(ctx context.Context, in *SetBotBehaviorRequest, opts ...grpc.CallOption) (*SetBotBehaviorResponse, error)
	// SendBotCommand 向 Bot 发送命令。
	SendBotCommand(ctx context.Context, in *SendBotCommandRequest, opts ...grpc.CallOption) (*SendBotCommandResponse, error)
	// RunBotScript 在指定 Bot 上执行脚本。
	RunBotScript(ctx context.Context, in *RunBotScriptRequest, opts ...grpc.CallOption) (*RunBotScriptResponse, error)
	// StreamBotEvents 订阅 Bot 事件流。
	StreamBotEvents(ctx context.Context, in *StreamBotEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BotEvent], error)
	// StreamPluginEvents 订阅某实例（或全部）探针经反向 WS 上报的事件流（connected/disconnected/玩家事件…）。
	StreamPluginEvents(ctx context.Context, in *StreamPluginEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PluginEvent], error)
	// SendPluginCommand CP 经 Worker 向探针下发治理/查询指令（踢/封/白名单/在线列表…）。
	SendPluginCommand(ctx context.Context, in *SendPluginCommandRequest, opts ...grpc.CallOption) (*SendPluginCommandResponse, error)
	// QueryServerState 查询子服全状态（在线列表/世界/TPS 等聚合），骨架，语义留下游。
	QueryServerState(ctx context.Context, in *QueryServerStateRequest, opts ...grpc.CallOption) (*QueryServerStateResponse, error)
	// GetVersion 返回 Worker 当前版本与平台信息，供 CP 自更新检查比对。
	GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error)
	// UpgradeWorker 令 Worker 下载指定二进制 → sha256 校验 → 替换自身 → 计划重启。
	// daemon 模式下不杀游戏服（ADR-003 wrapper 子进程与 Worker 主进程隔离，
	// Worker 重启后 RecoverDaemonInstances 经 PID 文件重连存活 wrapper）。
	// action="rollback" 时改为回滚本地升级前备份（FR-182，见 ADR-042），不下载。
	UpgradeWorker(ctx context.Context, in *UpgradeWorkerRequest, opts ...grpc.CallOption) (*UpgradeWorkerResponse, error)
}

type workerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerServiceClient(cc grpc.ClientConnInterface) WorkerServiceClient {
	return &workerServiceClient{cc}
}

func (c *workerServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, WorkerService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerService_ServiceDesc.Streams[0], WorkerService_Heartbeat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HeartbeatRequest, HeartbeatResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_HeartbeatClient = grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatResponse]

func (c *workerServiceClient) CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (*CreateInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateInstanceResponse)
	err := c.cc.Invoke(ctx, WorkerService_CreateInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) StartInstance(ctx context.Context, in *InstanceActionRequest, opts ...grpc.CallOption) (*InstanceActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceActionResponse)
	err := c.cc.Invoke(ctx, WorkerService_StartInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) StopInstance(ctx context.Context, in *InstanceActionRequest, opts ...grpc.CallOption) (*InstanceActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceActionResponse)
	err := c.cc.Invoke(ctx, WorkerService_StopInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) RestartInstance(ctx context.Context, in *InstanceActionRequest, opts ...grpc.CallOption) (*InstanceActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceActionResponse)
	err := c.cc.Invoke(ctx, WorkerService_RestartInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) KillInstance(ctx context.Context, in *InstanceActionRequest, opts ...grpc.CallOption) (*InstanceActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceActionResponse)
	err := c.cc.Invoke(ctx, WorkerService_KillInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) SendCommand(ctx context.Context, in *SendCommandRequest, opts ...grpc.CallOption) (*SendCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendCommandResponse)
	err := c.cc.Invoke(ctx, WorkerService_SendCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) GetInstanceStatus(ctx context.Context, in *InstanceActionRequest, opts ...grpc.CallOption) (*GetInstanceStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInstanceStatusResponse)
	err := c.cc.Invoke(ctx, WorkerService_GetInstanceStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (*ListInstancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInstancesResponse)
	err := c.cc.Invoke(ctx, WorkerService_ListInstances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) StreamInstanceEvents(ctx context.Context, in *StreamInstanceEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InstanceEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerService_ServiceDesc.Streams[1], WorkerService_StreamInstanceEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamInstanceEventsRequest, InstanceEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_StreamInstanceEventsClient = grpc.ServerStreamingClient[InstanceEvent]

func (c *workerServiceClient) IssueTerminalToken(ctx context.Context, in *IssueTerminalTokenRequest, opts ...grpc.CallOption) (*IssueTerminalTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueTerminalTokenResponse)
	err := c.cc.Invoke(ctx, WorkerService_IssueTerminalToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, WorkerService_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadFileResponse)
	err := c.cc.Invoke(ctx, WorkerService_ReadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteFileResponse)
	err := c.cc.Invoke(ctx, WorkerService_WriteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFileResponse)
	err := c.cc.Invoke(ctx, WorkerService_DeleteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) RenameFile(ctx context.Context, in *RenameFileRequest, opts ...grpc.CallOption) (*RenameFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenameFileResponse)
	err := c.cc.Invoke(ctx, WorkerService_RenameFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) DownloadArchive(ctx context.Context, in *DownloadArchiveRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadArchiveChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerService_ServiceDesc.Streams[2], WorkerService_DownloadArchive_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadArchiveRequest, DownloadArchiveChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_DownloadArchiveClient = grpc.ServerStreamingClient[DownloadArchiveChunk]

func (c *workerServiceClient) SearchFiles(ctx context.Context, in *SearchFilesRequest, opts ...grpc.CallOption) (*SearchFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchFilesResponse)
	err := c.cc.Invoke(ctx, WorkerService_SearchFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) ListArchiveEntries(ctx context.Context, in *ListArchiveEntriesRequest, opts ...grpc.CallOption) (*ListArchiveEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListArchiveEntriesResponse)
	err := c.cc.Invoke(ctx, WorkerService_ListArchiveEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) ReadArchiveEntry(ctx context.Context, in *ReadArchiveEntryRequest, opts ...grpc.CallOption) (*ReadArchiveEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadArchiveEntryResponse)
	err := c.cc.Invoke(ctx, WorkerService_ReadArchiveEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) DecompileClass(ctx context.Context, in *DecompileClassRequest, opts ...grpc.CallOption) (*DecompileClassResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecompileClassResponse)
	err := c.cc.Invoke(ctx, WorkerService_DecompileClass_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) ListConfigFiles(ctx context.Context, in *ListConfigFilesRequest, opts ...grpc.CallOption) (*ListConfigFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConfigFilesResponse)
	err := c.cc.Invoke(ctx, WorkerService_ListConfigFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) ReadConfig(ctx context.Context, in *ReadConfigRequest, opts ...grpc.CallOption) (*ReadConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadConfigResponse)
	err := c.cc.Invoke(ctx, WorkerService_ReadConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) WriteConfig(ctx context.Context, in *WriteConfigRequest, opts ...grpc.CallOption) (*WriteConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteConfigResponse)
	err := c.cc.Invoke(ctx, WorkerService_WriteConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) ValidateConfig(ctx context.Context, in *ValidateConfigRequest, opts ...grpc.CallOption) (*ValidateConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateConfigResponse)
	err := c.cc.Invoke(ctx, WorkerService_ValidateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) GetNodeMetrics(ctx context.Context, in *GetNodeMetricsRequest, opts ...grpc.CallOption) (*GetNodeMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeMetricsResponse)
	err := c.cc.Invoke(ctx, WorkerService_GetNodeMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) GetInstanceMetrics(ctx context.Context, in *GetInstanceMetricsRequest, opts ...grpc.CallOption) (*GetInstanceMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInstanceMetricsResponse)
	err := c.cc.Invoke(ctx, WorkerService_GetInstanceMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) ListJDKs(ctx context.Context, in *ListJDKsRequest, opts ...grpc.CallOption) (*ListJDKsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJDKsResponse)
	err := c.cc.Invoke(ctx, WorkerService_ListJDKs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) InstallJDK(ctx context.Context, in *InstallJDKRequest, opts ...grpc.CallOption) (*InstallJDKResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallJDKResponse)
	err := c.cc.Invoke(ctx, WorkerService_InstallJDK_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) RemoveJDK(ctx context.Context, in *RemoveJDKRequest, opts ...grpc.CallOption) (*RemoveJDKResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveJDKResponse)
	err := c.cc.Invoke(ctx, WorkerService_RemoveJDK_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) DownloadCore(ctx context.Context, in *DownloadCoreRequest, opts ...grpc.CallOption) (*DownloadCoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadCoreResponse)
	err := c.cc.Invoke(ctx, WorkerService_DownloadCore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) DeployServerProbe(ctx context.Context, in *DeployServerProbeRequest, opts ...grpc.CallOption) (*DeployServerProbeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeployServerProbeResponse)
	err := c.cc.Invoke(ctx, WorkerService_DeployServerProbe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) CloneWorkDir(ctx context.Context, in *CloneWorkDirRequest, opts ...grpc.CallOption) (*CloneWorkDirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloneWorkDirResponse)
	err := c.cc.Invoke(ctx, WorkerService_CloneWorkDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListImagesResponse)
	err := c.cc.Invoke(ctx, WorkerService_ListImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) PullImage(ctx context.Context, in *PullImageRequest, opts ...grpc.CallOption) (*PullImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullImageResponse)
	err := c.cc.Invoke(ctx, WorkerService_PullImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) RemoveImage(ctx context.Context, in *RemoveImageRequest, opts ...grpc.CallOption) (*RemoveImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveImageResponse)
	err := c.cc.Invoke(ctx, WorkerService_RemoveImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) CreateBackup(ctx context.Context, in *CreateBackupRequest, opts ...grpc.CallOption) (*CreateBackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBackupResponse)
	err := c.cc.Invoke(ctx, WorkerService_CreateBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) RestoreBackup(ctx context.Context, in *RestoreBackupRequest, opts ...grpc.CallOption) (*RestoreBackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreBackupResponse)
	err := c.cc.Invoke(ctx, WorkerService_RestoreBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) CreateBot(ctx context.Context, in *CreateBotRequest, opts ...grpc.CallOption) (*CreateBotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBotResponse)
	err := c.cc.Invoke(ctx, WorkerService_CreateBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) DeleteBot(ctx context.Context, in *DeleteBotRequest, opts ...grpc.CallOption) (*DeleteBotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBotResponse)
	err := c.cc.Invoke(ctx, WorkerService_DeleteBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) ListBots(ctx context.Context, in *ListBotsRequest, opts ...grpc.CallOption) (*ListBotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBotsResponse)
	err := c.cc.Invoke(ctx, WorkerService_ListBots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) SetBotBehavior(ctx context.Context, in *SetBotBehaviorRequest, opts ...grpc.CallOption) (*SetBotBehaviorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetBotBehaviorResponse)
	err := c.cc.Invoke(ctx, WorkerService_SetBotBehavior_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) SendBotCommand(ctx context.Context, in *SendBotCommandRequest, opts ...grpc.CallOption) (*SendBotCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendBotCommandResponse)
	err := c.cc.Invoke(ctx, WorkerService_SendBotCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) RunBotScript(ctx context.Context, in *RunBotScriptRequest, opts ...grpc.CallOption) (*RunBotScriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunBotScriptResponse)
	err := c.cc.Invoke(ctx, WorkerService_RunBotScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) StreamBotEvents(ctx context.Context, in *StreamBotEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BotEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerService_ServiceDesc.Streams[3], WorkerService_StreamBotEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamBotEventsRequest, BotEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_StreamBotEventsClient = grpc.ServerStreamingClient[BotEvent]

func (c *workerServiceClient) StreamPluginEvents(ctx context.Context, in *StreamPluginEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PluginEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerService_ServiceDesc.Streams[4], WorkerService_StreamPluginEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamPluginEventsRequest, PluginEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_StreamPluginEventsClient = grpc.ServerStreamingClient[PluginEvent]

func (c *workerServiceClient) SendPluginCommand(ctx context.Context, in *SendPluginCommandRequest, opts ...grpc.CallOption) (*SendPluginCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendPluginCommandResponse)
	err := c.cc.Invoke(ctx, WorkerService_SendPluginCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) QueryServerState(ctx context.Context, in *QueryServerStateRequest, opts ...grpc.CallOption) (*QueryServerStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryServerStateResponse)
	err := c.cc.Invoke(ctx, WorkerService_QueryServerState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVersionResponse)
	err := c.cc.Invoke(ctx, WorkerService_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) UpgradeWorker(ctx context.Context, in *UpgradeWorkerRequest, opts ...grpc.CallOption) (*UpgradeWorkerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpgradeWorkerResponse)
	err := c.cc.Invoke(ctx, WorkerService_UpgradeWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServiceServer is the server API for WorkerService service.
// All implementations must embed UnimplementedWorkerServiceServer
// for forward compatibility.
//
// WorkerService 定义 Control Plane 与 Worker Node 之间的 gRPC 服务。
type WorkerServiceServer interface {
	// Register Worker Node 首次启动时注册到 Control Plane。
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Heartbeat 双向心跳流，Worker 上报资源指标。
	Heartbeat(grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatResponse]) error
	// CreateInstance 在指定 Worker 上创建实例。
	CreateInstance(context.Context, *CreateInstanceRequest) (*CreateInstanceResponse, error)
	// StartInstance 启动实例。
	StartInstance(context.Context, *InstanceActionRequest) (*InstanceActionResponse, error)
	// StopInstance 停止实例。
	StopInstance(context.Context, *InstanceActionRequest) (*InstanceActionResponse, error)
	// RestartInstance 重启实例。
	RestartInstance(context.Context, *InstanceActionRequest) (*InstanceActionResponse, error)
	// KillInstance 强制终止实例。
	KillInstance(context.Context, *InstanceActionRequest) (*InstanceActionResponse, error)
	// SendCommand 向实例发送命令。
	SendCommand(context.Context, *SendCommandRequest) (*SendCommandResponse, error)
	// GetInstanceStatus 获取实例状态。
	GetInstanceStatus(context.Context, *InstanceActionRequest) (*GetInstanceStatusResponse, error)
	// ListInstances 列出 Worker 上所有实例。
	ListInstances(context.Context, *ListInstancesRequest) (*ListInstancesResponse, error)
	// StreamInstanceEvents 订阅实例事件流。
	StreamInstanceEvents(*StreamInstanceEventsRequest, grpc.ServerStreamingServer[InstanceEvent]) error
	// IssueTerminalToken 签发一次性终端连接 token。
	IssueTerminalToken(context.Context, *IssueTerminalTokenRequest) (*IssueTerminalTokenResponse, error)
	// ListFiles 列出实例工作目录下的文件。
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	// ReadFile 读取文件内容。
	ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error)
	// WriteFile 写入文件内容。
	WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error)
	// DeleteFile 删除文件。
	DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error)
	// RenameFile 重命名文件。
	RenameFile(context.Context, *RenameFileRequest) (*RenameFileResponse, error)
	// DownloadArchive 把选中的文件/目录（目录递归）即时打包为 zip 并分块流式返回（FR-070 批量下载）。
	DownloadArchive(*DownloadArchiveRequest, grpc.ServerStreamingServer[DownloadArchiveChunk]) error
	// SearchFiles 对实例工作目录做全文搜索或文件名快速打开（FR-074，见 ADR-017）。
	// Worker 维护本地持久倒排索引（var/index/，增量更新），查询返回命中文件+行+片段。
	SearchFiles(context.Context, *SearchFilesRequest) (*SearchFilesResponse, error)
	// ListArchiveEntries 列出归档（jar/zip）内全部条目（Go archive/zip，不起进程；FR-075，见 ADR-018）。
	ListArchiveEntries(context.Context, *ListArchiveEntriesRequest) (*ListArchiveEntriesResponse, error)
	// ReadArchiveEntry 读取归档内某条目内容，流式截断到上限（FR-075）。
	ReadArchiveEntry(context.Context, *ReadArchiveEntryRequest) (*ReadArchiveEntryResponse, error)
	// DecompileClass 经实例/系统 JDK 跑 CFR 反编译工作目录内 class/jar（或归档内某 class）为 Java 源码（FR-075，见 ADR-018）。
	DecompileClass(context.Context, *DecompileClassRequest) (*DecompileClassResponse, error)
	// ListConfigFiles 列出可管理配置文件。
	ListConfigFiles(context.Context, *ListConfigFilesRequest) (*ListConfigFilesResponse, error)
	// ReadConfig 读取配置文件并解析。
	ReadConfig(context.Context, *ReadConfigRequest) (*ReadConfigResponse, error)
	// WriteConfig 写入配置文件。
	WriteConfig(context.Context, *WriteConfigRequest) (*WriteConfigResponse, error)
	// ValidateConfig 校验配置内容。
	ValidateConfig(context.Context, *ValidateConfigRequest) (*ValidateConfigResponse, error)
	// GetNodeMetrics 获取节点指标。
	GetNodeMetrics(context.Context, *GetNodeMetricsRequest) (*GetNodeMetricsResponse, error)
	// GetInstanceMetrics 获取实例指标。
	GetInstanceMetrics(context.Context, *GetInstanceMetricsRequest) (*GetInstanceMetricsResponse, error)
	// ListJDKs 列出 Worker 本地已注册/探测到的 JDK 目录。
	ListJDKs(context.Context, *ListJDKsRequest) (*ListJDKsResponse, error)
	// InstallJDK 下载并安装指定 JDK 到 Worker 托管目录。
	InstallJDK(context.Context, *InstallJDKRequest) (*InstallJDKResponse, error)
	// RemoveJDK 删除 Worker 托管的 JDK 目录。
	RemoveJDK(context.Context, *RemoveJDKRequest) (*RemoveJDKResponse, error)
	// DownloadCore 下载服务端核心 jar 到实例工作目录（FR-034 一键开服）。
	DownloadCore(context.Context, *DownloadCoreRequest) (*DownloadCoreResponse, error)
	// DeployServerProbe 部署 ServerProbe 监控探针 jar 与 config 到实例 plugins 目录（FR-010）。
	DeployServerProbe(context.Context, *DeployServerProbeRequest) (*DeployServerProbeResponse, error)
	// CloneWorkDir 复制源实例工作目录到目标实例工作目录，排除运行态文件（FR-036 一键复制）。
	CloneWorkDir(context.Context, *CloneWorkDirRequest) (*CloneWorkDirResponse, error)
	// ListImages 列出 Worker 本机 Docker 镜像。
	ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error)
	// PullImage 从 registry 拉取镜像到 Worker 本机（建实例选镜像前置）。
	PullImage(context.Context, *PullImageRequest) (*PullImageResponse, error)
	// RemoveImage 删除 Worker 本机 Docker 镜像。
	RemoveImage(context.Context, *RemoveImageRequest) (*RemoveImageResponse, error)
	// CreateBackup 将实例工作目录打包为 tar.gz 落到节点数据根 var/backups/。
	// 增量备份据 base_manifest 仅打包新增/变化文件；可选上传到远程存储后端。
	CreateBackup(context.Context, *CreateBackupRequest) (*CreateBackupResponse, error)
	// RestoreBackup 按备份链顺序（全量基 + 各增量）回放归档到实例工作目录；
	// 远程归档先据 storage 拉回本地再回放。
	RestoreBackup(context.Context, *RestoreBackupRequest) (*RestoreBackupResponse, error)
	// CreateBot 在 Worker 上创建 Bot 连接。
	CreateBot(context.Context, *CreateBotRequest) (*CreateBotResponse, error)
	// DeleteBot 停止并删除 Bot。
	DeleteBot(context.Context, *DeleteBotRequest) (*DeleteBotResponse, error)
	// ListBots 列出 Worker 上所有 Bot。
	ListBots(context.Context, *ListBotsRequest) (*ListBotsResponse, error)
	// SetBotBehavior 切换 Bot 行为模式。
	SetBotBehavior(context.Context, *SetBotBehaviorRequest) (*SetBotBehaviorResponse, error)
	// SendBotCommand 向 Bot 发送命令。
	SendBotCommand(context.Context, *SendBotCommandRequest) (*SendBotCommandResponse, error)
	// RunBotScript 在指定 Bot 上执行脚本。
	RunBotScript(context.Context, *RunBotScriptRequest) (*RunBotScriptResponse, error)
	// StreamBotEvents 订阅 Bot 事件流。
	StreamBotEvents(*StreamBotEventsRequest, grpc.ServerStreamingServer[BotEvent]) error
	// StreamPluginEvents 订阅某实例（或全部）探针经反向 WS 上报的事件流（connected/disconnected/玩家事件…）。
	StreamPluginEvents(*StreamPluginEventsRequest, grpc.ServerStreamingServer[PluginEvent]) error
	// SendPluginCommand CP 经 Worker 向探针下发治理/查询指令（踢/封/白名单/在线列表…）。
	SendPluginCommand(context.Context, *SendPluginCommandRequest) (*SendPluginCommandResponse, error)
	// QueryServerState 查询子服全状态（在线列表/世界/TPS 等聚合），骨架，语义留下游。
	QueryServerState(context.Context, *QueryServerStateRequest) (*QueryServerStateResponse, error)
	// GetVersion 返回 Worker 当前版本与平台信息，供 CP 自更新检查比对。
	GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error)
	// UpgradeWorker 令 Worker 下载指定二进制 → sha256 校验 → 替换自身 → 计划重启。
	// daemon 模式下不杀游戏服（ADR-003 wrapper 子进程与 Worker 主进程隔离，
	// Worker 重启后 RecoverDaemonInstances 经 PID 文件重连存活 wrapper）。
	// action="rollback" 时改为回滚本地升级前备份（FR-182，见 ADR-042），不下载。
	UpgradeWorker(context.Context, *UpgradeWorkerRequest) (*UpgradeWorkerResponse, error)
	mustEmbedUnimplementedWorkerServiceServer()
}

// UnimplementedWorkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerServiceServer struct{}

func (UnimplementedWorkerServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedWorkerServiceServer) Heartbeat(grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatResponse]) error {
	return status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedWorkerServiceServer) CreateInstance(context.Context, *CreateInstanceRequest) (*CreateInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateInstance not implemented")
}
func (UnimplementedWorkerServiceServer) StartInstance(context.Context, *InstanceActionRequest) (*InstanceActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartInstance not implemented")
}
func (UnimplementedWorkerServiceServer) StopInstance(context.Context, *InstanceActionRequest) (*InstanceActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopInstance not implemented")
}
func (UnimplementedWorkerServiceServer) RestartInstance(context.Context, *InstanceActionRequest) (*InstanceActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartInstance not implemented")
}
func (UnimplementedWorkerServiceServer) KillInstance(context.Context, *InstanceActionRequest) (*InstanceActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KillInstance not implemented")
}
func (UnimplementedWorkerServiceServer) SendCommand(context.Context, *SendCommandRequest) (*SendCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendCommand not implemented")
}
func (UnimplementedWorkerServiceServer) GetInstanceStatus(context.Context, *InstanceActionRequest) (*GetInstanceStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstanceStatus not implemented")
}
func (UnimplementedWorkerServiceServer) ListInstances(context.Context, *ListInstancesRequest) (*ListInstancesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInstances not implemented")
}
func (UnimplementedWorkerServiceServer) StreamInstanceEvents(*StreamInstanceEventsRequest, grpc.ServerStreamingServer[InstanceEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamInstanceEvents not implemented")
}
func (UnimplementedWorkerServiceServer) IssueTerminalToken(context.Context, *IssueTerminalTokenRequest) (*IssueTerminalTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueTerminalToken not implemented")
}
func (UnimplementedWorkerServiceServer) ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedWorkerServiceServer) ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedWorkerServiceServer) WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedWorkerServiceServer) DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedWorkerServiceServer) RenameFile(context.Context, *RenameFileRequest) (*RenameFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameFile not implemented")
}
func (UnimplementedWorkerServiceServer) DownloadArchive(*DownloadArchiveRequest, grpc.ServerStreamingServer[DownloadArchiveChunk]) error {
	return status.Error(codes.Unimplemented, "method DownloadArchive not implemented")
}
func (UnimplementedWorkerServiceServer) SearchFiles(context.Context, *SearchFilesRequest) (*SearchFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchFiles not implemented")
}
func (UnimplementedWorkerServiceServer) ListArchiveEntries(context.Context, *ListArchiveEntriesRequest) (*ListArchiveEntriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListArchiveEntries not implemented")
}
func (UnimplementedWorkerServiceServer) ReadArchiveEntry(context.Context, *ReadArchiveEntryRequest) (*ReadArchiveEntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadArchiveEntry not implemented")
}
func (UnimplementedWorkerServiceServer) DecompileClass(context.Context, *DecompileClassRequest) (*DecompileClassResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DecompileClass not implemented")
}
func (UnimplementedWorkerServiceServer) ListConfigFiles(context.Context, *ListConfigFilesRequest) (*ListConfigFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConfigFiles not implemented")
}
func (UnimplementedWorkerServiceServer) ReadConfig(context.Context, *ReadConfigRequest) (*ReadConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadConfig not implemented")
}
func (UnimplementedWorkerServiceServer) WriteConfig(context.Context, *WriteConfigRequest) (*WriteConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteConfig not implemented")
}
func (UnimplementedWorkerServiceServer) ValidateConfig(context.Context, *ValidateConfigRequest) (*ValidateConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateConfig not implemented")
}
func (UnimplementedWorkerServiceServer) GetNodeMetrics(context.Context, *GetNodeMetricsRequest) (*GetNodeMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeMetrics not implemented")
}
func (UnimplementedWorkerServiceServer) GetInstanceMetrics(context.Context, *GetInstanceMetricsRequest) (*GetInstanceMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstanceMetrics not implemented")
}
func (UnimplementedWorkerServiceServer) ListJDKs(context.Context, *ListJDKsRequest) (*ListJDKsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJDKs not implemented")
}
func (UnimplementedWorkerServiceServer) InstallJDK(context.Context, *InstallJDKRequest) (*InstallJDKResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InstallJDK not implemented")
}
func (UnimplementedWorkerServiceServer) RemoveJDK(context.Context, *RemoveJDKRequest) (*RemoveJDKResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveJDK not implemented")
}
func (UnimplementedWorkerServiceServer) DownloadCore(context.Context, *DownloadCoreRequest) (*DownloadCoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DownloadCore not implemented")
}
func (UnimplementedWorkerServiceServer) DeployServerProbe(context.Context, *DeployServerProbeRequest) (*DeployServerProbeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeployServerProbe not implemented")
}
func (UnimplementedWorkerServiceServer) CloneWorkDir(context.Context, *CloneWorkDirRequest) (*CloneWorkDirResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloneWorkDir not implemented")
}
func (UnimplementedWorkerServiceServer) ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListImages not implemented")
}
func (UnimplementedWorkerServiceServer) PullImage(context.Context, *PullImageRequest) (*PullImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PullImage not implemented")
}
func (UnimplementedWorkerServiceServer) RemoveImage(context.Context, *RemoveImageRequest) (*RemoveImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveImage not implemented")
}
func (UnimplementedWorkerServiceServer) CreateBackup(context.Context, *CreateBackupRequest) (*CreateBackupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBackup not implemented")
}
func (UnimplementedWorkerServiceServer) RestoreBackup(context.Context, *RestoreBackupRequest) (*RestoreBackupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreBackup not implemented")
}
func (UnimplementedWorkerServiceServer) CreateBot(context.Context, *CreateBotRequest) (*CreateBotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBot not implemented")
}
func (UnimplementedWorkerServiceServer) DeleteBot(context.Context, *DeleteBotRequest) (*DeleteBotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBot not implemented")
}
func (UnimplementedWorkerServiceServer) ListBots(context.Context, *ListBotsRequest) (*ListBotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBots not implemented")
}
func (UnimplementedWorkerServiceServer) SetBotBehavior(context.Context, *SetBotBehaviorRequest) (*SetBotBehaviorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetBotBehavior not implemented")
}
func (UnimplementedWorkerServiceServer) SendBotCommand(context.Context, *SendBotCommandRequest) (*SendBotCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendBotCommand not implemented")
}
func (UnimplementedWorkerServiceServer) RunBotScript(context.Context, *RunBotScriptRequest) (*RunBotScriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunBotScript not implemented")
}
func (UnimplementedWorkerServiceServer) StreamBotEvents(*StreamBotEventsRequest, grpc.ServerStreamingServer[BotEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamBotEvents not implemented")
}
func (UnimplementedWorkerServiceServer) StreamPluginEvents(*StreamPluginEventsRequest, grpc.ServerStreamingServer[PluginEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamPluginEvents not implemented")
}
func (UnimplementedWorkerServiceServer) SendPluginCommand(context.Context, *SendPluginCommandRequest) (*SendPluginCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendPluginCommand not implemented")
}
func (UnimplementedWorkerServiceServer) QueryServerState(context.Context, *QueryServerStateRequest) (*QueryServerStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryServerState not implemented")
}
func (UnimplementedWorkerServiceServer) GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedWorkerServiceServer) UpgradeWorker(context.Context, *UpgradeWorkerRequest) (*UpgradeWorkerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpgradeWorker not implemented")
}
func (UnimplementedWorkerServiceServer) mustEmbedUnimplementedWorkerServiceServer() {}
func (UnimplementedWorkerServiceServer) testEmbeddedByValue()                       {}

// UnsafeWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServiceServer will
// result in compilation errors.
type UnsafeWorkerServiceServer interface {
	mustEmbedUnimplementedWorkerServiceServer()
}

func RegisterWorkerServiceServer(s grpc.ServiceRegistrar, srv WorkerServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerService_ServiceDesc, srv)
}

func _WorkerService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_Heartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkerServiceServer).Heartbeat(&grpc.GenericServerStream[HeartbeatRequest, HeartbeatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_HeartbeatServer = grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatResponse]

func _WorkerService_CreateInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).CreateInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_CreateInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).CreateInstance(ctx, req.(*CreateInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_StartInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).StartInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_StartInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).StartInstance(ctx, req.(*InstanceActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_StopInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).StopInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_StopInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).StopInstance(ctx, req.(*InstanceActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_RestartInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).RestartInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_RestartInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).RestartInstance(ctx, req.(*InstanceActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_KillInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).KillInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_KillInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).KillInstance(ctx, req.(*InstanceActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_SendCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).SendCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_SendCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).SendCommand(ctx, req.(*SendCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_GetInstanceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).GetInstanceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_GetInstanceStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).GetInstanceStatus(ctx, req.(*InstanceActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_ListInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).ListInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_ListInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).ListInstances(ctx, req.(*ListInstancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_StreamInstanceEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamInstanceEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerServiceServer).StreamInstanceEvents(m, &grpc.GenericServerStream[StreamInstanceEventsRequest, InstanceEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_StreamInstanceEventsServer = grpc.ServerStreamingServer[InstanceEvent]

func _WorkerService_IssueTerminalToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueTerminalTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).IssueTerminalToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_IssueTerminalToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).IssueTerminalToken(ctx, req.(*IssueTerminalTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).ListFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_ReadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).ReadFile(ctx, req.(*ReadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_WriteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).WriteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_WriteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).WriteFile(ctx, req.(*WriteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_RenameFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).RenameFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_RenameFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).RenameFile(ctx, req.(*RenameFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_DownloadArchive_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadArchiveRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerServiceServer).DownloadArchive(m, &grpc.GenericServerStream[DownloadArchiveRequest, DownloadArchiveChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_DownloadArchiveServer = grpc.ServerStreamingServer[DownloadArchiveChunk]

func _WorkerService_SearchFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).SearchFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_SearchFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).SearchFiles(ctx, req.(*SearchFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_ListArchiveEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArchiveEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).ListArchiveEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_ListArchiveEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).ListArchiveEntries(ctx, req.(*ListArchiveEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_ReadArchiveEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadArchiveEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).ReadArchiveEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_ReadArchiveEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).ReadArchiveEntry(ctx, req.(*ReadArchiveEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_DecompileClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecompileClassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).DecompileClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_DecompileClass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).DecompileClass(ctx, req.(*DecompileClassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_ListConfigFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConfigFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).ListConfigFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_ListConfigFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).ListConfigFiles(ctx, req.(*ListConfigFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_ReadConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).ReadConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_ReadConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).ReadConfig(ctx, req.(*ReadConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_WriteConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).WriteConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_WriteConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).WriteConfig(ctx, req.(*WriteConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_ValidateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).ValidateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_ValidateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).ValidateConfig(ctx, req.(*ValidateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_GetNodeMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).GetNodeMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_GetNodeMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).GetNodeMetrics(ctx, req.(*GetNodeMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_GetInstanceMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).GetInstanceMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_GetInstanceMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).GetInstanceMetrics(ctx, req.(*GetInstanceMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_ListJDKs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJDKsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).ListJDKs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_ListJDKs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).ListJDKs(ctx, req.(*ListJDKsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_InstallJDK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallJDKRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).InstallJDK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_InstallJDK_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).InstallJDK(ctx, req.(*InstallJDKRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_RemoveJDK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveJDKRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).RemoveJDK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_RemoveJDK_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).RemoveJDK(ctx, req.(*RemoveJDKRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_DownloadCore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadCoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).DownloadCore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_DownloadCore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).DownloadCore(ctx, req.(*DownloadCoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_DeployServerProbe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployServerProbeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).DeployServerProbe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_DeployServerProbe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).DeployServerProbe(ctx, req.(*DeployServerProbeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_CloneWorkDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloneWorkDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).CloneWorkDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_CloneWorkDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).CloneWorkDir(ctx, req.(*CloneWorkDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_ListImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).ListImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_ListImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).ListImages(ctx, req.(*ListImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_PullImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).PullImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_PullImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).PullImage(ctx, req.(*PullImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_RemoveImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).RemoveImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_RemoveImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).RemoveImage(ctx, req.(*RemoveImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_CreateBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).CreateBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_CreateBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).CreateBackup(ctx, req.(*CreateBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_RestoreBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).RestoreBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_RestoreBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).RestoreBackup(ctx, req.(*RestoreBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_CreateBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).CreateBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_CreateBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).CreateBot(ctx, req.(*CreateBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_DeleteBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).DeleteBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_DeleteBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).DeleteBot(ctx, req.(*DeleteBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_ListBots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).ListBots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_ListBots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).ListBots(ctx, req.(*ListBotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_SetBotBehavior_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBotBehaviorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).SetBotBehavior(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_SetBotBehavior_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).SetBotBehavior(ctx, req.(*SetBotBehaviorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_SendBotCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendBotCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).SendBotCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_SendBotCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).SendBotCommand(ctx, req.(*SendBotCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_RunBotScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunBotScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).RunBotScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_RunBotScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).RunBotScript(ctx, req.(*RunBotScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_StreamBotEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamBotEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerServiceServer).StreamBotEvents(m, &grpc.GenericServerStream[StreamBotEventsRequest, BotEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_StreamBotEventsServer = grpc.ServerStreamingServer[BotEvent]

func _WorkerService_StreamPluginEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamPluginEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerServiceServer).StreamPluginEvents(m, &grpc.GenericServerStream[StreamPluginEventsRequest, PluginEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_StreamPluginEventsServer = grpc.ServerStreamingServer[PluginEvent]

func _WorkerService_SendPluginCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPluginCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).SendPluginCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_SendPluginCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).SendPluginCommand(ctx, req.(*SendPluginCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_QueryServerState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryServerStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).QueryServerState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_QueryServerState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).QueryServerState(ctx, req.(*QueryServerStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).GetVersion(ctx, req.(*GetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_UpgradeWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradeWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).UpgradeWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_UpgradeWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).UpgradeWorker(ctx, req.(*UpgradeWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerService_ServiceDesc is the grpc.ServiceDesc for WorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "worker.WorkerService",
	HandlerType: (*WorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _WorkerService_Register_Handler,
		},
		{
			MethodName: "CreateInstance",
			Handler:    _WorkerService_CreateInstance_Handler,
		},
		{
			MethodName: "StartInstance",
			Handler:    _WorkerService_StartInstance_Handler,
		},
		{
			MethodName: "StopInstance",
			Handler:    _WorkerService_StopInstance_Handler,
		},
		{
			MethodName: "RestartInstance",
			Handler:    _WorkerService_RestartInstance_Handler,
		},
		{
			MethodName: "KillInstance",
			Handler:    _WorkerService_KillInstance_Handler,
		},
		{
			MethodName: "SendCommand",
			Handler:    _WorkerService_SendCommand_Handler,
		},
		{
			MethodName: "GetInstanceStatus",
			Handler:    _WorkerService_GetInstanceStatus_Handler,
		},
		{
			MethodName: "ListInstances",
			Handler:    _WorkerService_ListInstances_Handler,
		},
		{
			MethodName: "IssueTerminalToken",
			Handler:    _WorkerService_IssueTerminalToken_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _WorkerService_ListFiles_Handler,
		},
		{
			MethodName: "ReadFile",
			Handler:    _WorkerService_ReadFile_Handler,
		},
		{
			MethodName: "WriteFile",
			Handler:    _WorkerService_WriteFile_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _WorkerService_DeleteFile_Handler,
		},
		{
			MethodName: "RenameFile",
			Handler:    _WorkerService_RenameFile_Handler,
		},
		{
			MethodName: "SearchFiles",
			Handler:    _WorkerService_SearchFiles_Handler,
		},
		{
			MethodName: "ListArchiveEntries",
			Handler:    _WorkerService_ListArchiveEntries_Handler,
		},
		{
			MethodName: "ReadArchiveEntry",
			Handler:    _WorkerService_ReadArchiveEntry_Handler,
		},
		{
			MethodName: "DecompileClass",
			Handler:    _WorkerService_DecompileClass_Handler,
		},
		{
			MethodName: "ListConfigFiles",
			Handler:    _WorkerService_ListConfigFiles_Handler,
		},
		{
			MethodName: "ReadConfig",
			Handler:    _WorkerService_ReadConfig_Handler,
		},
		{
			MethodName: "WriteConfig",
			Handler:    _WorkerService_WriteConfig_Handler,
		},
		{
			MethodName: "ValidateConfig",
			Handler:    _WorkerService_ValidateConfig_Handler,
		},
		{
			MethodName: "GetNodeMetrics",
			Handler:    _WorkerService_GetNodeMetrics_Handler,
		},
		{
			MethodName: "GetInstanceMetrics",
			Handler:    _WorkerService_GetInstanceMetrics_Handler,
		},
		{
			MethodName: "ListJDKs",
			Handler:    _WorkerService_ListJDKs_Handler,
		},
		{
			MethodName: "InstallJDK",
			Handler:    _WorkerService_InstallJDK_Handler,
		},
		{
			MethodName: "RemoveJDK",
			Handler:    _WorkerService_RemoveJDK_Handler,
		},
		{
			MethodName: "DownloadCore",
			Handler:    _WorkerService_DownloadCore_Handler,
		},
		{
			MethodName: "DeployServerProbe",
			Handler:    _WorkerService_DeployServerProbe_Handler,
		},
		{
			MethodName: "CloneWorkDir",
			Handler:    _WorkerService_CloneWorkDir_Handler,
		},
		{
			MethodName: "ListImages",
			Handler:    _WorkerService_ListImages_Handler,
		},
		{
			MethodName: "PullImage",
			Handler:    _WorkerService_PullImage_Handler,
		},
		{
			MethodName: "RemoveImage",
			Handler:    _WorkerService_RemoveImage_Handler,
		},
		{
			MethodName: "CreateBackup",
			Handler:    _WorkerService_CreateBackup_Handler,
		},
		{
			MethodName: "RestoreBackup",
			Handler:    _WorkerService_RestoreBackup_Handler,
		},
		{
			MethodName: "CreateBot",
			Handler:    _WorkerService_CreateBot_Handler,
		},
		{
			MethodName: "DeleteBot",
			Handler:    _WorkerService_DeleteBot_Handler,
		},
		{
			MethodName: "ListBots",
			Handler:    _WorkerService_ListBots_Handler,
		},
		{
			MethodName: "SetBotBehavior",
			Handler:    _WorkerService_SetBotBehavior_Handler,
		},
		{
			MethodName: "SendBotCommand",
			Handler:    _WorkerService_SendBotCommand_Handler,
		},
		{
			MethodName: "RunBotScript",
			Handler:    _WorkerService_RunBotScript_Handler,
		},
		{
			MethodName: "SendPluginCommand",
			Handler:    _WorkerService_SendPluginCommand_Handler,
		},
		{
			MethodName: "QueryServerState",
			Handler:    _WorkerService_QueryServerState_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _WorkerService_GetVersion_Handler,
		},
		{
			MethodName: "UpgradeWorker",
			Handler:    _WorkerService_UpgradeWorker_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Heartbeat",
			Handler:       _WorkerService_Heartbeat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamInstanceEvents",
			Handler:       _WorkerService_StreamInstanceEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DownloadArchive",
			Handler:       _WorkerService_DownloadArchive_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamBotEvents",
			Handler:       _WorkerService_StreamBotEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamPluginEvents",
			Handler:       _WorkerService_StreamPluginEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/worker.proto",
}
